In [1]:
# Google Colab 운영체제 확인
import platform
print(platform.platform())

Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic


In [2]:
# 텐서플로우 불러오기, 버전 확인
import tensorflow as tf
print(tf.__version__)

2.4.1


## 랜덤한 수 생성

In [3]:
# 랜덤한 수 얻기 (균일 분포)
rand = tf.random.uniform([1],0,1)
print(rand)

tf.Tensor([0.12306917], shape=(1,), dtype=float32)


In [4]:
# 랜덤한 수 여러 개 얻기 (균일 분포)
rand = tf.random.uniform([4],0,1)
print(rand)

tf.Tensor([0.9960002  0.12071526 0.32582045 0.8938416 ], shape=(4,), dtype=float32)


In [5]:
# 랜덤한 수 여러 개 얻기 (정규 분포)
rand = tf.random.normal([4],0,1)
print(rand)

tf.Tensor([-0.3227001   0.36942035 -0.40484625  0.32267934], shape=(4,), dtype=float32)


## 뉴런 만들기

In [6]:
# sigmoid 함수 : 0~1 사이값으로 제한해서 리턴

import math

def sigmoid(x):
    # 상수 e의 제곱을 계산하기 위해 math.exp() 사용
    # x에 시그모이드 함수를 취한 값
    return 1 / (1 + math.exp(-x))

In [7]:
# 문제 : 뉴런의 입력과 출력 정의 - 입력이 1일때 기대 출력이 0이 되는 뉴런 만들어 보기
# 기대 출력이 0이라 할 경우 차를 error라 함
# 뉴런의 학습 = 이 에러가 0에 가까워지게 해서 출력으로 기댓값에 가까운 값을 얻는 것

x = 1
y = 0

# 가중치로 정규 분포의 랜덤한 값
w = tf.random.normal([1],0,1)  # 정규 분포의 난수 구하는 함수 


output = sigmoid(x * w)
print(output)

0.38137220157906093


In [8]:
# 경사 하강법을 이용한 뉴런의 학습
# w에 입력과 학습률과 에러를 곱한 값을 더해줌
# 학습률은 w를 업데이트하는 정도
# a = 0.1로 설정

'''
0~999까지 1000번 반복
error 는 기대출력인 y에서 실제 출력인 output 빼기
여러번 반복해서 x가 1일때 y값이 0에 가까워짐을 확인
'''
for i in range(1000):
    output = sigmoid(x * w)
    error = y - output
    w = w + x * 0.1 * error
    
    if i % 100 == 99:
        print('순번 : ', i, ' 에러 : ', error, ' 출력 : ', output)

순번 :  99  에러 :  -0.09263524036416097  출력 :  0.09263524036416097
순번 :  199  에러 :  -0.04961400803446758  출력 :  0.04961400803446758
순번 :  299  에러 :  -0.03359260927397521  출력 :  0.03359260927397521
순번 :  399  에러 :  -0.025321930291052196  출력 :  0.025321930291052196
순번 :  499  에러 :  -0.020293836346138454  출력 :  0.020293836346138454
순번 :  599  에러 :  -0.01692052807669938  출력 :  0.01692052807669938
순번 :  699  에러 :  -0.014503048088767371  출력 :  0.014503048088767371
순번 :  799  에러 :  -0.01268679153658078  출력 :  0.01268679153658078
순번 :  899  에러 :  -0.01127284239147663  출력 :  0.01127284239147663
순번 :  999  에러 :  -0.010141252554322787  출력 :  0.010141252554322787


In [9]:
# x=0 일 때 y=1 을 얻는 뉴런의 학습시키기
# 편향의 필요성 인지하기

'''
문제발생 : error와 출력 모두 0.5로 변하지 않음
입력값 0  따라서 w에 더해지는 데이터는 없음, 즉 1000번 실행하는 동안 w 값 변동 없음
'''

x = 0
y = 1
w = tf.random.normal([1],0,1)

for i in range(1000):
    output = sigmoid(x * w)
    error = y - output
    w = w + x * 0.1 * error
    
    if i % 100 == 99:
       print('순번 : ', i, ' 에러 : ', error, ' 출력 : ', output)

순번 :  99  에러 :  0.5  출력 :  0.5
순번 :  199  에러 :  0.5  출력 :  0.5
순번 :  299  에러 :  0.5  출력 :  0.5
순번 :  399  에러 :  0.5  출력 :  0.5
순번 :  499  에러 :  0.5  출력 :  0.5
순번 :  599  에러 :  0.5  출력 :  0.5
순번 :  699  에러 :  0.5  출력 :  0.5
순번 :  799  에러 :  0.5  출력 :  0.5
순번 :  899  에러 :  0.5  출력 :  0.5
순번 :  999  에러 :  0.5  출력 :  0.5


In [10]:
# 해결책 : 편향(bias)이라는 것 적용
# x=0 일 때 y=1 을 얻는 뉴런의 학습에 편향을 더함

'''
입력으로는 늘 한쪽으로 치우진 고정된 값 가령 1을 받아서 입력으로 0을 받았을 때 
뉴런이 아무것도 배우지 못하는 상황 방지

편향은 w 처럼 난수로 초기화되며 뉴런에 더해져서 출력 계산

결론 : error는 0에 가까워짐, output은 1에 가까워짐
'''

x = 0
y = 1
w = tf.random.normal([1],0,1)
b = tf.random.normal([1],0,1)

for i in range(1000):
    output = sigmoid(x * w + 1 * b)
    error = y - output
    w = w + x * 0.1 * error
    b = b + 1 * 0.1 * error
    
    if i % 100 == 99:
        print('순번 : ', i, ' 에러 : ', error, ' 출력 : ', output)

순번 :  99  에러 :  0.0963741362340872  출력 :  0.9036258637659128
순번 :  199  에러 :  0.050717324248411355  출력 :  0.9492826757515886
순번 :  299  에러 :  0.03410319005267559  출력 :  0.9658968099473244
순번 :  399  에러 :  0.025613373087948643  출력 :  0.9743866269120514
순번 :  499  에러 :  0.020481531823238752  출력 :  0.9795184681767612
순번 :  599  에러 :  0.01705122235030687  출력 :  0.9829487776496931
순번 :  699  에러 :  0.014599211131432921  출력 :  0.9854007888685671
순번 :  799  에러 :  0.01276043110721048  출력 :  0.9872395688927895
순번 :  899  에러 :  0.011331080437559704  출력 :  0.9886689195624403
순번 :  999  에러 :  0.010188413876725089  출력 :  0.9898115861232749
